version: '3.1'
services:

  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080